### ISSUE TITLE
New layer and new encoding system for keying the branches on the event tree

### ISSUE THREAD

**Issue by horaciobam** [PoonLab/HexSE#114] opened 2022-05-10 16:30 UTC
A new layer considering ORFs and their possible combinations is required. See [diagram on issue 112](https://github.com/PoonLab/HexSE/issues/112#issuecomment-1118625410).

**Comment by horaciobam** [comment] 2022-05-10 21:37
Required steps:
- [ ] 1. **Sort Reading Frames (RF)** according to their position on their genome. 
- [ ] 2. **Detect possible combinations of Reading frames**. For example, if `seq` has three reading frames in positions `[0,33], [30,45], [80,95]`, the possible combinations are: 
    * `000`: nts in No RF
    * `100`: nts in RF1 only
    * `010`: nts in RF2 only
    * `001`: nts in RF3 only
    * `110`: nts in RFs 1 and RF2
- [ ] 3. **Convert binary codes to decimals** (e.g. `110` would be `6` , `000` would be `0`, `100` would be `4` and so on)
- [ ] 4. **Assign decimal key to nucleotide:** for each nucleotide, detect the reading frames that it is part of (e.g. in previous `seq`, `nt` in position 31 would be in `110`) and assign them the appropriate decimal key.
- [ ] 5. **Select omega category:** for each nucleotide, define the omega categories that will be applied to its mutation rate. 
(this step is currently happening in `set_substitution_rate()`)
    For example:
    * Nucleotides in no reading frame: no further keys
    * Nucleotides in one RF:
        * key `0`: mutation is synonymous, apply `dN/dS=1`
        * key `1`: mutation is non-synonymous, apply first omega category
        * key `2`: mutation is non-synonymous, apply second omega category
    * Nucleotides in two RFs:
        * key `(0,1)`: mutation is syn in first RF, non-syn in second RF. Apply first omega category for RF2
        * key `(2,1)`: mutation is non-syn in both RFs. Apply second omega category for first RF and first category for RF2

- [ ] 6. **Store nucleotide** on the Event Tree according to its keys. 
- [ ] 7. **Modify `get_substitution` function**: in `simulation.py`, edit substitution function such as it traverses all layers on the tree using the new key system.

**Comment by horaciobam** [comment] 2022-05-11 21:42
On [last commit](https://github.com/PoonLab/HexSE/commit/d9eda39326465f89d0113787bc6a6c4cc5dc2190), every reading frame will have an array of coordenates as `orf_map` that we can later map to a decimal. 

```python
{   '+': [   {   'coords': [[0, 837]],
                 'omega_classes': 2,
                 'omega_shape': 1.7,
                 'omega_values': [0.2969606107777804, 1.0630393892187806],
                 'orf_map': array([1, 0])},
             {   'coords': [[156, 837]],
                 'omega_classes': 2,
                 'omega_shape': 1.2,
                 'omega_values': [0.1691149716766538, 0.7908850282996809],
                 'orf_map': array([0, 1])}],
    '-': []}
```

**Comment by ArtPoon** [comment] 2022-05-17 18:21
Regarding the use of decimal numbers to represent the binary vector keys of which ORFs a position in the genome is associated with - since it is unlikely that any position will be involved in more than three ORFs, these binary vectors should end up being rather sparse and mapping them to decimal values is probably overkill.  So if it's easier to retain the binary tuples as keys, then I'd just go ahead with that approach.

**Comment by horaciobam** [comment] 2022-05-17 20:34
Thanks @ArtPoon, I agree.

**Comment by horaciobam** [comment] 2022-05-19 01:14
Before adding the layer for omega and categories and nucleotides on the tips, `event_tree` is looking like:
```python
{ 'to_nt': { 'A': { 'from_nt': { 'A': None,
                                 'C': { 'mu1': { (0, 0, 0, 1): { 'omega': {},
                                                                 'prob': 0},
                                                 (0, 0, 1, 0): { 'omega': {},
                                                                 'prob': 0},
                                                 (0, 1, 0, 0): { 'omega': {},
                                                                 'prob': 0},
                                                 (1, 0, 0, 0): { 'omega': {},
                                                                 'prob': 0}},
                                        'mu2': { (0, 0, 0, 1): { 'omega': {},
                                                                 'prob': 0},
                                                 (0, 0, 1, 0): { 'omega': {},
                                                                 'prob': 0},
                                                 (0, 1, 0, 0): { 'omega': {},
                                                                 'prob': 0},
                                                 (1, 0, 0, 0): { 'omega': {},
                                                                 'prob': 0}}},
                                 'G': { 'mu1': { (0, 0, 0, 1): { 'omega': {},
                                                                 'prob': 0},
                                                 (0, 0, 1, 0): { 'omega': {},
                                                                 'prob': 0},
                                                 (0, 1, 0, 0): { 'omega': {},
                                                                 'prob': 0},
                                                 (1, 0, 0, 0): { 'omega': {},
                                                                 'prob': 0}},
                                        'mu2': { (0, 0, 0, 1): { 'omega': {},
                                                                 'prob': 0},
                                                 (0, 0, 1, 0): { 'omega': {},
                                                                 'prob': 0},
                                                 (0, 1, 0, 0): { 'omega': {},
                                                                 'prob': 0},
                                                 (1, 0, 0, 0): { 'omega': {},
                                                                 'prob': 0}}},
                                 'T': { 'mu1': { (0, 0, 0, 1): { 'omega': {},
                                                                 'prob': 0},
                                                 (0, 0, 1, 0): { 'omega': {},
                                                                 'prob': 0},
                                                 (0, 1, 0, 0): { 'omega': {},
                                                                 'prob': 0},
                                                 (1, 0, 0, 0): { 'omega': {},
                                                                 'prob': 0}},
                                        'mu2': { (0, 0, 0, 1): { 'omega': {},
                                                                 'prob': 0},
                                                 (0, 0, 1, 0): { 'omega': {},
                                                                 'prob': 0},
                                                 (0, 1, 0, 0): { 'omega': {},
                                                                 'prob': 0},
                                                 (1, 0, 0, 0): { 'omega': {},
                                                                 'prob': 0}}}}},
             'C': { 'from_nt': { 'A': { 'mu1': { (0, 0, 0, 1): { 'omega': {},
                                                                 'prob': 0},
                                                 (0, 0, 1, 0): { 'omega': {},
                                                                 'prob': 0},
                                                 (0, 1, 0, 0): { 'omega': {},
                                                                 'prob': 0},
                                                 (1, 0, 0, 0): { 'omega': {},
                                                                 'prob': 0}},
                                        'mu2': { (0, 0, 0, 1): { 'omega': {},
                                                                 'prob': 0},
                                                 (0, 0, 1, 0): { 'omega': {},
                                                                 'prob': 0},
                                                 (0, 1, 0, 0): { 'omega': {},
                                                                 'prob': 0},
                                                 (1, 0, 0, 0): { 'omega': {},
                                                                 'prob': 0}}},
                                 'C': None,
``` 

Functions on `sequence_info` where tree traversal needs to be updated:

- `nt_in_event_tree`
- `compute_probability`
- `count_events_per_layer`
-  `count_nts_on_event_tree`

Following step: modify `set_total_omegas` to find keys of omega values as tuples with the number of the category for each reading frame.

**Comment by ArtPoon** [comment] 2022-05-19 14:54
The problem is that we need to generate a set of tuples that correspond to every combination of overlaps that occur in the genome, and no more.  In this part of the code:
https://github.com/PoonLab/HexSE/blob/0d94097d39ccdbb0fbd987b0e6903b5d3ce9d557/hexse/sequence_info.py#L85-L94

we are iterating through codons in each ORF, and telling every nucleotide which codons it belongs to.  We can reverse the flow of information in a subsequent loop:
```python
# initialize a list with all tuples for sites in one ORF only, and for sites that are not in any ORF
num_orfs = len(self.orfs)
base_tuple = [0] * num_orfs
all_maps = {}
for nt in nt_sequence:
    orf_map = sum([codon.orf["orf_map"] for codon in nt.codons])  # element-wide addition of np.array
    # check if this orf_map has been seen before, if not then update all_maps
```

**Comment by horaciobam** [comment] 2022-05-20 19:52
![rect38334](https://user-images.githubusercontent.com/42696510/169601497-ce14a232-d753-48cb-9f1c-1c9b957914ef.png)

**Comment by horaciobam** [comment] 2022-06-01 14:01
For the omega layer, instead of having a tuple of as many indexes as ORFs for the nucleotide, we decided to initialize the omega key as a list of `-1` with length equal to the number of orfs in the sequence (`[ -1,  -1, -1, -1, -1]`) and then select the omegas and set their index on the list:

```python
{'A': None, 'C': [0, 3, -1, -1, -1], 'G': [1, 0, -1, -1, -1], 'T': [0, 2, -1, -1, -1]}
```

This nucleotide is part of the first 2 reading frames, and when mutating to `C`, we apply `0.2` and `1.4` from the omega values from the lists: `[0.2, 0.5, 1.2]` for the first ORF and `[0.1, 0.4, 0.7, 1.4]` for the second ORF.

```python
 for to_nt in NUCLEOTIDES:
            
            
            if to_nt == current_nt:
                sub_rates[to_nt] = None
                selected_omegas[to_nt] = None
            else:
                # Apply global substitution rate and stationary nucleotide frequency
                sub_rates[to_nt] = self.global_rate * self.pi[current_nt]
                if self.is_transv(current_nt, to_nt):
                    sub_rates[to_nt] *= self.kappa

                
                if nt.codons:
                # For each codon, find the combination of omegas that will affect it according to the codons it is part of
                # E.g.: [2, 3, -1, -1, -1] represent a nucleotide in two reading frames where both mutations are non-syn. 
                # Note: "-1" means that nt is not part of that ORF

                    chosen_omegas = list(self.number_orfs)  # Initialize chosen omegas as list of "-1" with len equal to number of ORFs
                    for codon in nt.codons:
                        codon_orf = codon.orf['orf_map']
                        orf_index = np.where(codon_orf==1)[0][0]  # The position with a 1 indicates the ORF for the codon

                        # If mutation does not introduce a STOP and nucleotide is not part of a START codon
                        if not self.is_start_stop_codon(nt, to_nt):
                            pos_in_codon = codon.nt_in_pos(nt)
                            
                            # If mutation is non-synonymous, select one omega index to an omega_values for the orf
                            if codon.is_nonsyn(pos_in_codon, to_nt):
            
                                omega_values = codon.orf['omega_values']
                                print(omega_values)
                                #Randomly select one of the omegas
                                omega_index = random.randrange(len(omega_values))
                                chosen_omegas[orf_index] = omega_index

                            # If mutation is synonymous, no omega applied
                            else:
                                chosen_omegas[orf_index] = None

                        # Mutation introduces or destroys a STOP or nt is part of a START
                        else: 
                            chosen_omegas = None  # Nucleotides that shouldn't mutate. Don't include them on the Event Tree
                    selected_omegas[to_nt] = chosen_omegas  # Store omega list used to describe the substitution
                
                selected_cat = random.choice(list(self.cat_values))  # Randomly select one of the mu values (mutation rate) 
                sub_rates[to_nt] *= self.cat_values[selected_cat]
                my_cat_keys[to_nt] = selected_cat

```

**Comment by horaciobam** [comment] 2022-06-01 21:38
Updated key system:
![simulation_keys](https://user-images.githubusercontent.com/42696510/171506296-d280a228-01b5-4489-b2ae-ed8e08eea541.png)

**Comment by horaciobam** [comment] 2022-06-02 22:47
Finished Event Tree nucleotide storing, looking like:

```python
{ 'to_nt': { 'A': { 'from_nt': { 'A': None,
                                 'C': { 'mu1': { 'nt_events': 402,
                                                 (0, 0, 0, 0, 0): { 'n_events': 181,
                                                                    (None, None, None, None, None): [ c844, c865, c867, c869, c906, c911, c914, c920, c929, c937, c959, c967, c992, c995, c1007, c1020, c1023, c1024, c1025, c1034, c1046, c1050, c1059, c1068, c1089, c1095, c1099, c1101, c1103, c1111, c1116, c1135, c1136, c1142, c1147, c1148, c1149, c1155, c1156, c1157, c1160, c1163, c1167, c1172, c1177, c1194, c1197, c1207, c1213, c1238, c1251, c1254, c1268, c1272, c1282, c1283, c1288, c1290, c1299, c1303, c1306, c1321, c1339, c1348, c1353, c1354, c1357, c1368, c1373, c1379, c1382, c1392, c1396, c1399, c1406, c1416, c1420, c1432, c1433, c1440, c1442, c1449, c1456, c1459, c1460, c1466, c1474, c1481, c1483, c1485, c1490, c1491, c1498, c1499, c1502, c1510, c1514, c1515, c1531, c1533, c1548, c1550, c1560, c1563, c1572, c1576, c1583, c1585, c1588, c1601, c1603, c1620, c1628, c1629, c1630, c1633, c1644, c1650, c1664, c1666, c1672, c1691, c1692, c1696, c1707, c1710, c1731, c1774, c1789, c1800, c1803, c1811, c1818, c1827, c1830, c1836, c1857, c1873, c1874, c1884, c1893, c2458, c2459, c2465, c2467, c2481, c2486, c2491, c2501, c2509, c2514, c2522, c2524, c2554, c2560, c2568, c2600, c2602, c2629, c2641, c2646, c2667, c2678, c2698, c2708, c2713, c2716, c2733, c2745, c2752, c2754, c2768, c2792, c2797, c2802, c2805, c2819, c2821, c2822, c2836, c2845]},
                                                 (0, 0, 0, 0, 1): { 'n_events': 52,
                                                                    (None, None, None, None, -1): [ c2893, c2929, c2956, c2980, c3019, c3064, c3100, c3103, c3106, c3112, c3172],
                                                                    (None, None, None, None, 0): [ c2891, c3018, c3020, c3050, c3068, c3093, c3096, c3099, c3167],
                                                                    (None, None, None, None, 1): [ c2861, c2926, c2931, c2965, c2973, c2977, c2979, c3000, c3004, c3024, c3049, c3084, c3110, c3125, c3128, c3135, c3165, c3176],
                                                                    (None, None, None, None, 2): [ c2865, c2868, c2872, c2892, c2899, c2917, c2937, c2955, c3051, c3075, c3102, c3134, c3141, c3157]},
                                                 (0, 0, 0, 1, 0): { 'n_events': 61,
                                                                    (None, None, None, -1, None): [ c2003, c2111, c2159, c2225, c2282, c2352, c2355, c2360, c2366, c2393, c2397, c2420, c2436],
                                                                    (None, None, None, 0, None): [ c1933, c1992, c2050, c2199, c2289, c2326, c2328, c2341, c2389, c2445],
                                                                    (None, None, None, 1, None): [ c1914, c1975, c2055, c2070, c2286, c2313, c2380],
                                                                    (None, None, None, 2, None): [ c1915, c2040, c2049, c2052, c2137, c2150, c2213, c2293, c2304, c2365, c2391, c2413],
                                                                    (None, None, None, 3, None): [ c1967, c1989, c2101, c2211, c2301, c2311, c2338, c2367, c2412, c2428],
                                                                    (None, None, None, 4, None): [ c1936, c1963, c1974, c1999, c2010, c2023, c2032, c2173, c2305]},
                                                 (1, 0, 0, 0, 0): { 'n_events': 18,
                                                                    (-1, None, None, None, None): [ c47, c68, c71, c107, c113],
                                                                    (0, None, None, None, None): [ c15, c24, c48, c112, c128, c143, c150],
                                                                    (1, None, None, None, None): [ c17, c22, c33, c90, c103, c111]},
                                                 (1, 0, 1, 0, 0): { 'n_events': 84,
                                                                    (-1, None, -1, None, None): [ c230, c293, c305, c329, c344, c374, c387, c398, c401, c407, c428, c494, c503, c519, c524, c560, c563, c599, c653, c668, c674, c719, c788],
                                                                    (0, None, 0, None, None): [ c417,
                                                                                                c468,
                                                                                                c688],
```
Following step: modify `simulation.py` to traverse the tree with new layer system and select mutations by calculating the probabilities for the branches.

**Comment by horaciobam** [comment] 2022-06-06 20:47
Once a mutation occur on `selected_nt`, we need to do the following:

1. Remove `selected_nt` from tips on the event tree
2. Run `set_substitution rates` for nucleotide under `new_state`
3. Re-locate nucleotide on the `Event Tree`
4. If nucleotide is part of codons, inform codons of the new state of the nucleotide and follow all the previous steps for the all nucleotides that shared codons with `selected_nt`

**Comment by horaciobam** [comment] 2022-06-08 22:12
Currently, updating the nucleotide information and their position on the `even_tree` is causing the following issue:
```console
laura@eva:~/Projects/ovrf$ python3 -m hexse.run_simulation tests/fixtures/HBV.fasta tests/fixtures/100_tree.newick tests/fixtures/test_HBV.yaml 

Started at:  2022-06-08 16:17:31.143306
Omitted orf: [1375, 1840] in [], has 3 STOP codons

Creating root sequence
Simulating on Branch Clade
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/laura/Projects/ovrf/hexse/run_simulation.py", line 465, in <module>
    main()
  File "/home/laura/Projects/ovrf/hexse/run_simulation.py", line 456, in main
    simulation.get_alignment(args.outfile)
  File "/home/laura/Projects/ovrf/hexse/simulation.py", line 288, in get_alignment
    final_tree = self.traverse_tree()
  File "/home/laura/Projects/ovrf/hexse/simulation.py", line 280, in traverse_tree
    clade.sequence = simulation.mutate_on_branch()
  File "/home/laura/Projects/ovrf/hexse/simulation.py", line 192, in mutate_on_branch
    self.remove_nt(adj_nt, selected_orf_combo)
  File "/home/laura/Projects/ovrf/hexse/simulation.py", line 225, in remove_nt
    my_branch.remove(selected_nt)
ValueError: list.remove(x): x not in list
```
The following is a diagram to keep track of changes once a mutation occurs:
![simulation_updates](https://user-images.githubusercontent.com/42696510/172726392-e9df87f0-0a06-4140-91a0-b09d1fe007ef.png)

**Closed as completed** 2022-06-16 19:38 UTC
